Dynavy/flashfood-project-backend

backend/app/Http/Controllers/CategoryController.php

FEAT(CategoryController): Add Crud methods.

---

backend/.gitignore
backend/database/migrations/2024_11_27_160216_create_categories_table.php

Feat(Categories): Categories table migration db.

---

backend/app/Models/Category.php

- Created the `Category` model in the `app/Models` directory using the artisan command.
- Added `$fillable` property for mass assignment protection on the `name` attribute.
- Set up a `belongsTo` relationship with the `Restaurant` model, preparing for future database interaction.
Closes #15

Created Category model with mass assignment and restaurant relation

---

backend/app/Http/Controllers/CategoryController.php

- Added validation for the name field to ensure it is a string, required and 50 characters max.
- Returned a JSON response with the created category and a success message.
Close #6

Created store method for CategoryController to handle category creation

---

backend/database/seeders/CategoriesTableSeeder.php
backend/database/seeders/DatabaseSeeder.php

- New template information has been generated on Categories table.
Closes #19

FEAT(CategoriesTableSeeder): added a seeder for the categories Table.

---

backend/database/factories/CategoryFactory.php
backend/database/seeders/CategoriesTableSeeder.php

- Created an array of real food to not generate random words for the Categories names.
Closes #20

REFACTOR(CategoriesSeeder):  CategoryFactory generates template data.

---

backend/app/Services/CategoryService.php
backend/app/Services/OfferService.php
backend/app/Services/RestaurantService.php
backend/app/Services/ReviewService.php
backend/app/Services/UserService.php

FEAT(services): services layers implemented.

---

backend/app/Http/Controllers/CategoryController.php
backend/app/Services/CategoryService.php

- Updated the CategoryController to delegate business logic to the service layer.
Closes #31

REFACTOR(store): Business Logic Moved to Service Layer.

---

backend/app/Http/Controllers/CategoryController.php
backend/app/Services/CategoryService.php

- Updated the CategoryController to delegate business logic to the service layer.
Close #35

REFACTOR(destroy): Business Logic Moved to Service Layer.

---

backend/app/Http/Controllers/CategoryController.php
backend/app/Services/CategoryService.php
backend/routes/api.php

- Implemented index() method to return a list of all categories
- Implemented show() method to return a specific category by ID
Closes #8 #9

FEAT(CategoryController): Implement index() and show() for Category.

---

backend/app/Services/ReviewService.php

REFACTOR(ReviewService): Change updateReview method to use findOrFail

---

backend/app/Services/RestaurantService.php

- Removed custom error logging and response handling.
- Re-threw exceptions to allow centralized handling via the global exception handler.
Close #54

REFACTOR(RestaurantService): exception handling in the `destroy` method.

---

backend/app/Exceptions/CustomExceptionHandler.php

- Deleted Handler.php file.
- Implemented a new CustomExceptionHandler.php file to manage the HTTP status errors.
Close #53.

FEAT(CustomExceptionHandler): new class to manage errors.

---

backend/app/Exceptions/CustomExceptionHandler.php

- Internal server error removed from the CustomExceptionHandler.
Close #42

REFACTOR(CustomExceptionHandler): removed status 500

---

backend/app/Services/ReviewService.php

REFACTOR(ReviewService): Change deleteReview method to use transactions.

---

backend/app/Services/ReviewService.php

REFACTOR(ReviewService): Change createReview() to store().

---

backend/app/Services/ReviewService.php

FEAT(ReviewService): Add index() and showByID.

---

backend/app/Http/Controllers/CategoryController.php
backend/app/Http/Controllers/RestaurantController.php

FIX(Handler): Move HTTP status logic out of CustomExceptionHandler.php

---

backend/app/Exceptions/CustomExceptionHandler.php
backend/routes/test.php
backend/tests/Feature/CustomExceptionHandlerTest.php
backend/tests/TestCase.php

-  Implemented custom HTTP error statuses for bad request (400), authentication (401), authorization (403), and too many requests (429).
- Added a new class for unit tests to ensure the custom exception handler functions as expected.
- `php artisan test` to run the tests.
Close #59

FEAT(CustomExceptionTest): Implemented status errors and tests.

---

backend/FlashFoods.postman_collection.json
backend/app/Http/Controllers/UserController.php
backend/app/Http/Requests/UserRequest.php
backend/app/Services/UserService.php
backend/database/seeders/UserTableSeeder.php
backend/routes/api.php

- Implemented full backend layers for the User module, including service, repository, and controller functionalities.
- Refactored existing logic to ensure consistency with new layers.
Closes #68

FEAT(Users): Update with complete backend layers

---

backend/bootstrap/app.php

- Configured Sanctum to work with stateful authentication for the SPA.
- Added statefulApi() middleware in app.php to handle secure API access.
Close #75

FEAT(app.php): configure Sanctum SPA authentication with stateful API middleware.

---

backend/_ide_helper.php
backend/composer.json
backend/composer.lock
backend/config/app.php

Integrate Laravel IDE Helper for enhanced IDE support

---

backend/app/Models/User.php

- Implemented a setPasswordAttribute mutator in the User model to hash passwords automatically before saving them to the database using Hash::make.
- Removed password from the casts property to avoid redundancy with the mutator.
Close #74.

FEAT(User): implemented automatic password hashing with a mutator.

---

backend/app/Http/Controllers/AuthController.php
backend/app/Http/Controllers/CategoryController.php
backend/app/Http/Controllers/FavoriteController.php
backend/app/Http/Controllers/OfferController.php
backend/app/Http/Controllers/RestaurantController.php
backend/app/Http/Controllers/ReviewController.php
backend/app/Http/Controllers/UserController.php

- Refactored all controllers to utilize Laravel's automatic dependency injection instead of manually instantiating services within the constructors.
Close #89.

Refactor controllers to use automatic dependency injection.

---

backend/.env.example

- Added Mailtrap configuration to .env.example for testing email functionality.
- Clarified that this configuration is for testing only and that a different service should be used in production.
Close #94.

CHORE(.env.example): updated .env.example for Mailtrap configuration.

---

backend/app/Mail/TestMail.php
backend/resources/views/emails/test-email.blade.php

- Added test email view for verifying Mailtrap setup.
- Created TestMail class in App\Mail to handle email testing.
Close #96.

FEAT: create view and email test functionality for Mailtrap configuration.

---

backend/app/Exceptions/CustomExceptionHandler.php

- Add Response return type declaration to render method.
- Improve type safety and code clarity.
- Follow PHP 8+ type hinting best practices.
Close #100

REFACTOR(CustomException): add explicit return type to render funciton.

---

backend/app/Http/Controllers/Auth/AuthController.php
backend/app/Http/Controllers/Auth/ForgotPasswordController.php
backend/app/Http/Controllers/Auth/ResetPasswordController.php
backend/app/Http/Controllers/Restaurant/CategoryController.php
backend/app/Http/Controllers/Restaurant/OfferController.php
backend/app/Http/Controllers/Restaurant/RestaurantController.php
backend/app/Http/Controllers/Review/ReviewController.php
backend/app/Http/Controllers/User/FavoriteController.php
backend/app/Http/Controllers/User/UserController.php

REFACTOR (Controllers): Use App\Http\Controllers\Controller; and update namespaces.

---

backend/routes/auth-test-routes.php
backend/routes/error-auth.php
backend/tests/Feature/AuthControllerTest.php
backend/tests/TestCase.php

- New auth-test-routes.php file has been created.
- References to the new file had been updated.
Closes #125.

Rename error-auth-test to auth-test-routes and update references.

---

backend/routes/handler-test-routes.php
backend/tests/Feature/CustomExceptionHandlerTest.php
backend/tests/TestCase.php

- New handler-test-routes.php file has been created.
- References to the new file had been updated.
Closes #126.

Rename error-test-routes to handler-test-routes and update references.

---

backend/tests/Feature/DatabaseEnvironmentTest.php

- Implemented checks for the testing environment and in-memory database (SQLITE).
- Added validation for the existence of required tables.
- Implemented structure validation for key tables and their columns.
- Included tests to ensure tables are not empty after migrations.
Closes #129.

FEAT(DatabaseEnvironmentTest): Add tests for environment, tables, and columns.
